sudo: required
service:
  - docker
env:
  global:
    # Set a GIT SHA to track your changes in deploy.sh
    - SHA=$(git rev-parse HEAD)

    # Disable prompts by GCP Cloud-SDK as this file will be run remotely automatically
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # Login to Travis CI using github Encrypted Service Account
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d

  # download google sdk | install sdk in /dev/null
  - curl https://sdk.cloud.google.com | bash > /dev/null;

  # source (run) the file path.bash.inc of google sdk
  - source $HOME/google-cloud-sdk/path.bash.inc

  # install kubectl command used in GCP
  - gcloud components update kubectl

  # login into gcp using a file containing our credentials called
  # service-account.json
  - gcloud auth activate-service-account --key-file service-account.json

  # Select a working GCP project
  - gcloud config set project multi-k8s-nh

  # Set k8s compute zone 
  - gcloud config set compute/zone europe-west2-a

  # Add the name of k8s cluster aka multi-cluster
  - gcloud container clusters get-credentials multi-cluster

  # Login into docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Build the testing dockerfile
  - docker build -t nabeelhamadal/react-test -f ./client/Dockerfile.dev ./client

# Testing using Travis CI
script:
  # Run test of the test dockerfile
  - docker run -e CI=true nabeelhamadal/react-test npm test

# Post testing by Travis CI
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main